version: '3.6'
services:
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "/wait && bundle exec rake db:migrate && bundle exec rake db:seed && bundle exec rake assets:precompile && bundle exec puma"
    ports:
      - 4004:4004
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://etd:etd@mysql/etd
      - PORT=4004
      - RAILS_SERVE_STATIC_FILES=true
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: etd
      MYSQL_USER: etd
      MYSQL_PASSWORD: etd
