defaults: &defaults
  app_name: "ETD"
  app_owner: "York University Libraries"
  app_maintenance: false
  app_maintenance_message: "ETD Application will be taken down for maintenance today from 12pm to 1pm.  We appologize for any inconvenience this may have caused."
  email_allow: true
  email_from: "noreply@library.yorku.ca"
  email_welcome_subject:  "Welcome to York University's Electronic Thesis and Dissertation (ETD) application"
  email_welcome_allow: true
  email_welcome_body: "Email body"
  email_status_change_allow: true
  email_status_change_subject: "The status of your thesis has been changed."
  email_status_change_body: "Status Change email text goes here"
  errors_email_subject_prefix: "[ETD Error] "
  errors_email_from: "'ETD Notifier' <etd-errors@your-instituttion.website>"
  errors_email_to: "your.email@your-instituttion.email"

test:
  <<: *defaults

development:
  <<: *defaults
