default: &default
  encoding: utf8
  adapter: <%= ENV["DB_ADAPTER"] || "mysql2" %>
  url: <%= ENV["DATABASE_URL"] %>
  reconnect: true
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 10000

development:
  <<: *default

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
